Added a minimal list of properties to change in local.env for dev
bento-platform/bento pull request #214
Opened 2024-01-24 20:59 UTC by dbujold

2024-01-24 21:07 UTC, davidlougheed requested changes

2024-01-24 21:07 UTC, davidlougheed commented on docs/installation.md
> +
also need to set WES client secret, which comes from the output of init-auth - also maybe adding extra caution again that further changes are needed in production

2024-01-25 14:10 UTC, dbujold commented
Revision done!

2024-01-25 15:01 UTC, davidlougheed approved these changes
lgtm

2024-01-25 16:04 UTC, merged