Created beacon config template, added bentoctl tool to copy files for beacon, katsu
bento-platform/bento pull request #234
Opened 2024-04-29 18:55 UTC by SanjeevLakhwani

- beacon config moved to etc/templates/beacon/beacon_config.json
-lib/beacon/beacon_config.json is git ignored
-added cli tool init-config <<service>> for beacon and katsu to copy the example configs to their respective locations

2024-04-29 19:10 UTC, v-rocheleau reviewed
Looks good, should this also be done for `beacon_cohort.json` while we are here @gsfk ?

2024-04-29 19:43 UTC, gsfk commented
> Looks good, should this also be done for `beacon_cohort.json` while we are here @gsfk ?

Yes, good catch, `beacon_cohort.json` should be handled in the same way. Hopefully soon we can eliminate this file entirely.

2024-05-01 12:19 UTC, gsfk commented
Just starting tests, now, first comment is that it probably needs some README additions

2024-05-01 13:07 UTC, gsfk requested changes
Okay, I guess the intended command for beacon is 

`./bentoctl.bash init-config beacon`

and simiilarly for katsu. This should be in the README somewhere. I wonder also if there's a use case for just `./bentoctl.bash init-config` that does katsu and beacon together. I guess this will come anyway when we manage to unify the config files. 

Otherwise this looks great, everything works as expected.

2024-05-06 15:25 UTC, davidlougheed requested changes

2024-05-06 15:25 UTC, davidlougheed commented on py_bentoctl/other_helpers.py
> +def _init_katsu(force: bool):
same here

2024-05-06 17:29 UTC, davidlougheed requested changes

2024-05-06 17:29 UTC, davidlougheed commented on docs/installation.md
> +### Beacon configuration
two newlines between `###` blocks

2024-05-06 17:37 UTC, davidlougheed approved these changes
lgtm

2024-05-06 17:46 UTC, gsfk commented
`./bentoctl.bash init-config beacon` gives me permission denied error, since config directory was created by root

2024-05-08 17:58 UTC, gsfk approved these changes

2024-05-10 11:05 UTC, merged